version: "3"
services:
  hub:
    image: selenium/hub:4.7.2
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.7.2
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.7.2
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module1:
    image: ssomanpfpt/selenium-docker   
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./search-result1:/usr/share/udemy/test-output
  search-module2:
    image: ssomanpfpt/selenium-docker   
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/usr/share/udemy/test-output
  book-flight-module1:
    image: ssomanpfpt/selenium-docker   
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result1:/usr/share/udemy/test-output
  book-flight-module2:
    image: ssomanpfpt/selenium-docker   
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result2:/usr/share/udemy/test-output